---
title: "Strategisk ordsky"
author: "Are Edvardsen, SKDE"
date: "10/10/2019"
output: ioslides_presentation
# output:
#   revealjs::revealjs_presentation:
#     self_contained: true
#     fig_height: 4
#     theme: beige
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
data("texts")
data("guris")
```

## Hvem er vi? Google vet alt
```{r gsky, warning=FALSE}
res <- strat::makeWordCloud(guris, type = "url", max.words = 50, colorPalette = "Set1")
```

## Stats
```{r gstats, echo=TRUE}
head(res$freqTable, 5)
```

## Analyse

```{r asky, warning=FALSE}
res <- strat::makeWordCloud(texts$anal, type = "text", max.words = 50, colorPalette = "PiYG")
```

## Stats
```{r astats, echo=TRUE}
head(res$freqTable, 5)
```

## Sørvis
```{r ssky, warning=FALSE}
res <- strat::makeWordCloud(texts$serv, type = "text", max.words = 50, colorPalette = "RdBu")
```

## Stats
```{r sstats, echo=TRUE}
head(res$freqTable, 5)
```

## Alle sammen sammen
```{r stratsky, warning=FALSE}
res <- strat::makeWordCloud(paste(texts$anal, texts$serv, collapse = ' '), type = "text", max.words = 50, colorPalette = "Purples")
```

## Stats
```{r stratstats, echo=TRUE}
head(res$freqTable, 5)
```